version: '3.8'
services:
  api_and_ros2:
    build: .
    container_name: fleetglue_take_home_assignment
    environment:
      - ROS_PACKAGE_PATH=/ros2_ws/src
    ports:
      - "3000:3000"
    networks:
      - fleetglue_network

networks:
  fleetglue_network:
    driver: bridge
